interface IEnv {
  PORT: number;
  NODE_ENV: string;
  OTP_TIMEOUT_IN_MINUTES: number;
  PAY_VIA_CRYPTO_TIMEOUT_IN_MINUTES: number;
  FIRST_CARD_BAN_MINUTES: number;
  SECOND_CARD_BAN_HOURS: number;
  CURRENT_API_URL: string;
  DATABASE_URL: string;
  HUMO_MIDDLEWARE_URL: string;
  HUMO_MIDDLEWARE_TOKEN: string;
  HUMO_SOAP_HOST: string;
  HUMO_SOAP_USERNAME: string;
  HUMO_SOAP_PASSWORD: string;
  HUMO_CENTER_ID: string;
  HUMO_POINT_CODE: string;
  PLAYMOBILE_USERNAME: string;
  PLAYMOBILE_PASSWORD: string;
  PLAYMOBILE_ENDPOINT: string;
  PLAYMOBILE_ORIGINATOR: string;
  UZCARD_API_URL: string;
  UZCARD_LOGIN: string;
  UZCARD_PASSWORD: string;
  P2P_COMISSION_IN_PERCENT: number;
  P2P_CASHBOX_ID: number;
  RABBITMQ_HOST: string;
  RABBITMQ_PORT: string;
  RABBITMQ_PASSWORD: string;
  RABBITMQ_USER: string;
}

export const env: IEnv = {
  PORT: +process.env.PORT || 3000,
  NODE_ENV: process.env.NODE_ENV || null,
  OTP_TIMEOUT_IN_MINUTES: +process.env.OTP_TIMEOUT_IN_MINUTES || 3,
  PAY_VIA_CRYPTO_TIMEOUT_IN_MINUTES:
    +process.env.PAY_VIA_CRYPTO_TIMEOUT_IN_MINUTES || 10,
  FIRST_CARD_BAN_MINUTES: +process.env.FIRST_CARD_BAN_MINUTES || 10,
  SECOND_CARD_BAN_HOURS: +process.env.SECOND_CARD_BAN_HOURS || 24,
  CURRENT_API_URL: process.env.CURRENT_API_URL || null,
  DATABASE_URL: process.env.DATABASE_URL,
  HUMO_MIDDLEWARE_URL: process.env.HUMO_MIDDLEWARE_URL,
  HUMO_MIDDLEWARE_TOKEN: process.env.HUMO_MIDDLEWARE_TOKEN,
  HUMO_SOAP_HOST: process.env.HUMO_SOAP_HOST,
  HUMO_SOAP_USERNAME: process.env.HUMO_SOAP_USERNAME,
  HUMO_SOAP_PASSWORD: process.env.HUMO_SOAP_PASSWORD,
  HUMO_CENTER_ID: process.env.HUMO_CENTER_ID,
  HUMO_POINT_CODE: process.env.HUMO_POINT_CODE,
  PLAYMOBILE_USERNAME: process.env.PLAYMOBILE_USERNAME,
  PLAYMOBILE_PASSWORD: process.env.PLAYMOBILE_PASSWORD,
  PLAYMOBILE_ENDPOINT: process.env.PLAYMOBILE_ENDPOINT,
  PLAYMOBILE_ORIGINATOR: process.env.PLAYMOBILE_ORIGINATOR,
  UZCARD_API_URL: process.env.UZCARD_API_URL,
  UZCARD_LOGIN: process.env.UZCARD_LOGIN,
  UZCARD_PASSWORD: process.env.UZCARD_PASSWORD,
  P2P_COMISSION_IN_PERCENT: +process.env.P2P_COMISSION_IN_PERCENT || 1,
  P2P_CASHBOX_ID: +process.env.P2P_CASHBOX_ID || 2,
  RABBITMQ_HOST: process.env.RABBITMQ_HOST,
  RABBITMQ_PORT: process.env.RABBITMQ_PORT,
  RABBITMQ_PASSWORD: process.env.RABBITMQ_PASSWORD,
  RABBITMQ_USER: process.env.RABBITMQ_USER,
};
